ekf_filter_node:
  ros__parameters:
    frequency: 3.0  # Reduced from 5Hz: Mission-critical to 3Hz on Pi hardware. See fea_slam/config/ekf.yaml for full config.
    sensor_timeout: 1.5
    two_d_mode: true
    publish_tf: true

    map_frame: map
    odom_frame: odom
    base_link_frame: base_footprint
    world_frame: odom

    imu0: /imu/data_raw
    # Only use Angular Velocity and Linear Acceleration
    imu0_config: [false, false, false,
                  false, false, false,
                  false, false, false,
                  true,  true,  true,
                  true,  true,  true]
    imu0_differential: true 
    imu0_remove_gravitational_acceleration: true