#!/bin/bash

# FEA-SLAM Quick Start Guide
# This script helps you understand the startup sequence

echo "╔════════════════════════════════════════════════════════════╗"
echo "║           FEA-SLAM Framework - Startup Guide               ║"
echo "╚════════════════════════════════════════════════════════════╝"
echo ""

# Source the workspace
cd /home/pi/FEA_SLAM_WS
source install/setup.bash

echo "📋 STARTUP OPTIONS:"
echo ""
echo "1️⃣  TEST ROBOT DESCRIPTION (Recommended First Step)"
echo "   → Visualize robot model in RViz without hardware"
echo "   → Command: ros2 launch fea_slam display.launch.py"
echo ""
echo "2️⃣  FULL SYSTEM - ALL COMPONENTS"
echo "   → Robot + LiDAR + SLAM + Visualization"
echo "   → ⚠️  Requires hardware connected (LiDAR on /dev/ttyUSB*)"
echo "   → Command: ros2 launch fea_slam robot_full.launch.py"
echo ""
echo "3️⃣  STEP-BY-STEP (Recommended for First Time)"
echo "   → Start components individually for debugging"
echo "   → See below for sequence"
echo ""
echo "════════════════════════════════════════════════════════════"
echo ""
echo "🚀 RECOMMENDED STARTUP SEQUENCE (First Time):"
echo ""
echo "Step 1: Test Robot Description"
echo "  Terminal 1:"
echo "    ros2 launch fea_slam display.launch.py"
echo "  → You should see the robot in RViz"
echo ""
echo "Step 2: Check Hardware Connections"
echo "    ls -l /dev/ttyUSB*"
echo "  → Should show YDLiDAR device"
echo "  → If not found, connect LiDAR or add user to dialout group"
echo ""
echo "Step 3: Launch Full System"
echo "  Terminal 1:"
echo "    ros2 launch fea_slam robot_full.launch.py"
echo ""
echo "Step 4: Verify Topics (in new terminal)"
echo "  Terminal 2:"
echo "    ros2 topic list"
echo "    ros2 topic echo /scan --once    # Check LiDAR data"
echo "    ros2 topic echo /map --once     # Check SLAM map"
echo ""
echo "════════════════════════════════════════════════════════════"
echo ""
echo "🔍 WHAT TO CHOOSE NOW:"
echo ""

# Check if LiDAR is connected
if ls /dev/ttyUSB* 2>/dev/null | grep -q "ttyUSB"; then
    echo "✅ LiDAR detected on: $(ls /dev/ttyUSB* 2>/dev/null)"
    echo ""
    echo "👉 RECOMMENDED: Start with option 2 (Full System)"
    echo ""
    echo "Run this command:"
    echo "  ros2 launch fea_slam robot_full.launch.py"
else
    echo "⚠️  No USB devices found (LiDAR not connected)"
    echo ""
    echo "👉 RECOMMENDED: Start with option 1 (Test Robot Description)"
    echo ""
    echo "Run this command:"
    echo "  ros2 launch fea_slam display.launch.py"
    echo ""
    echo "After connecting LiDAR hardware, run:"
    echo "  ros2 launch fea_slam robot_full.launch.py"
fi

echo ""
echo "════════════════════════════════════════════════════════════"
echo ""
echo "💡 TIPS:"
echo "  • First time? Start with display.launch.py to verify robot model"
echo "  • Hardware ready? Use robot_full.launch.py for complete system"
echo "  • Need to debug? Launch components individually (see README.md)"
echo ""
echo "📚 More info: /home/pi/FEA_SLAM_WS/src/fea_slam/launch/README.md"
echo ""
